name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Install dependencies
      run: go mod tidy

    - name: Build project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image
      run: docker build -t cqupthub:v1 .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push cqupthub:v1

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@118.24.79.139 "docker pull cqupthub:v1 && docker run -d --restart unless-stopped -p 2001:8080 --network=cqupthub_net --name cqupthub"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}