name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update SSH client
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 118.24.79.139 >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o BatchMode=yes -o ConnectTimeout=30 -o StrictHostKeyChecking=no ubuntu@118.24.79.139 "echo 'SSH connection successful!'"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Install dependencies
      run: go mod tidy

    - name: Build project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image
      run: docker build -t oenvimor/website:v1 .

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push oenvimor/website:v1

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@118.24.79.139 "
          # Open the clash proxy
          sudo bash start.sh
          # Stop and remove existing container if it exists
          sudo docker stop cqupthub || true
          sudo docker rm cqupthub || true
          # Remove existing image if it exists
          sudo docker rmi oenvimor/website:v1 || true
          # Pull the latest image and run the container
          sudo docker pull oenvimor/website:v1
          sudo docker run -d --restart unless-stopped -p 2001:8080 --network=cqupthub_net --name cqupthub oenvimor/website:v1
        "
